pub mod claude_cli;
pub mod cli_ndjson;
pub mod cli_process;
pub mod cli_user;
pub mod client;
mod client_complete;
pub mod codex_cli;
pub mod cursor_cli;
pub mod json;
pub mod opencode_cli;
mod opencode_sessions;
pub mod prompt;
